version: 0.2

phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug assembleDebugAndroidTest
  post_build:
    commands:
      - aws s3 cp ./app/**/*.apk s3://howru-build-storage/howRU_build
artifacts:
  files:
     - './app/**/*.apk'
  discard-paths: yes
